/*
 * This file is generated by jOOQ.
 */
package org.shiloh.jooq.codegen.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 系统部门信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDept implements Serializable {

    private static final long serialVersionUID = 146335589;

    private Long   id;
    private String name;
    private String tel;

    public SysDept() {}

    public SysDept(SysDept value) {
        this.id = value.id;
        this.name = value.name;
        this.tel = value.tel;
    }

    public SysDept(
        Long   id,
        String name,
        String tel
    ) {
        this.id = id;
        this.name = name;
        this.tel = tel;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysDept (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(tel);

        sb.append(")");
        return sb.toString();
    }
}
