/*
 * This file is generated by jOOQ.
 */
package org.shiloh.jooq.codegen.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 系统用户信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserPojo implements Serializable {

    private static final long serialVersionUID = 1974694166;

    private Long    id;
    private String  username;
    private String  password;
    private Integer age;
    private String  sex;
    private String  email;
    private Long    deptId;

    public SysUserPojo() {}

    public SysUserPojo(SysUserPojo value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.age = value.age;
        this.sex = value.sex;
        this.email = value.email;
        this.deptId = value.deptId;
    }

    public SysUserPojo(
        Long    id,
        String  username,
        String  password,
        Integer age,
        String  sex,
        String  email,
        Long    deptId
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.age = age;
        this.sex = sex;
        this.email = email;
        this.deptId = deptId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getDeptId() {
        return this.deptId;
    }

    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUserPojo (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(age);
        sb.append(", ").append(sex);
        sb.append(", ").append(email);
        sb.append(", ").append(deptId);

        sb.append(")");
        return sb.toString();
    }
}
